----Master data for Country and Currency status
INSERT INTO CUSTOMER_SEARCH (CUSTOMER_ID, CUSTOMER_NAME, PANCARD_NUMBER) 
VALUES (CUSTOMER_SEARCH.nextval, 'JHON', 'BSAL9823CH')
;
INSERT INTO CUSTOMER_SEARCH (CUSTOMER_ID, CUSTOMER_NAME, PANCARD_NUMBER) 
VALUES (CUSTOMER_SEARCH.nextval, 'RAZOR', 'BZEPP4899Q')
;
INSERT INTO CUSTOMER_SEARCH (CUSTOMER_ID, CUSTOMER_NAME, PANCARD_NUMBER) 
VALUES (CUSTOMER_SEARCH.nextval, 'DAVE', 'BDHC9823CH')
;
INSERT INTO CUSTOMER_SEARCH (CUSTOMER_ID, CUSTOMER_NAME, PANCARD_NUMBER) 
VALUES (CUSTOMER_SEARCH.nextval, 'DJASEN', 'BQRDC5656S')
;